//! # Isolde init command
//!
//! Initialize a new Isolde project with a configuration file.

use std::fs;
use std::path::PathBuf;

use colored::Colorize;
use isolde_core::config::Config;
use isolde_core::{Error, Result};

/// Options for the init command
#[derive(Debug, Clone)]
pub struct InitOptions {
    /// Template to use (optional)
    pub template: Option<String>,

    /// Preset to use (optional)
    pub preset: Option<String>,

    /// Skip confirmation prompts
    pub yes: bool,

    /// Current working directory
    pub cwd: PathBuf,

    /// Project name (for non-interactive mode)
    pub name: Option<String>,

    /// Language version (optional)
    pub lang_version: Option<String>,

    /// Coding agent to use (claude-code, codex, gemini, aider)
    pub agent: String,

    /// Agent CLI version to install
    pub agent_version: String,

    /// HTTP proxy URL (optional)
    pub http_proxy: Option<String>,

    /// HTTPS proxy URL (optional)
    pub https_proxy: Option<String>,
}

impl Default for InitOptions {
    fn default() -> Self {
        Self {
            template: None,
            preset: None,
            yes: false,
            cwd: PathBuf::from("."),
            name: None,
            lang_version: None,
            agent: "claude-code".to_string(),
            agent_version: "latest".to_string(),
            http_proxy: None,
            https_proxy: None,
        }
    }
}

/// Generate configuration from a template name
fn generate_config_from_template(project_name: &str, template: &str, agent: &str, agent_version: &str) -> String {
    let (docker_image, runtime_section) = match template {
        "python" => (
            "mcr.microsoft.com/devcontainers/python:3.12",
            "runtime:\n  language: python\n  version: \"3.12\"\n  package_manager: uv\n  tools: []\n",
        ),
        "nodejs" => (
            "mcr.microsoft.com/devcontainers/javascript-node:22",
            "runtime:\n  language: nodejs\n  version: \"22\"\n  package_manager: pnpm\n  tools: []\n",
        ),
        "rust" => (
            "mcr.microsoft.com/devcontainers/rust:latest",
            "runtime:\n  language: rust\n  version: stable\n  package_manager: cargo\n  tools: []\n",
        ),
        "go" => (
            "mcr.microsoft.com/devcontainers/go:1.22",
            "runtime:\n  language: go\n  version: \"1.22\"\n  package_manager: go\n  tools: []\n",
        ),
        _ => (
            "mcr.microsoft.com/devcontainers/base:ubuntu",
            "",
        ),
    };

    let agent_options_section = agent_options_yaml(agent);

    format!(
        r#"# Isolde Configuration for {name}
# Generated from template: {template}
version: "0.1"
template: {template}

name: {name}
workspace:
  dir: ./project

docker:
  image: {image}
  build_args: []

# Coding agent configuration
agent:
  name: {agent}
  version: {agent_version}
  options:
{agent_options}

{runtime}
# Git configuration
git:
  generated: ignored
"#,
        name = project_name,
        template = template,
        image = docker_image,
        agent = agent,
        agent_version = agent_version,
        agent_options = agent_options_section,
        runtime = runtime_section,
    )
}

/// Generate a default isolde.yaml configuration
fn generate_default_config(project_name: &str, agent: &str, agent_version: &str) -> String {
    let agent_options_section = agent_options_yaml(agent);

    format!(
        r#"# Isolde Configuration for {name}
# Generated by isolde init
version: "0.1"

name: {name}
workspace:
  dir: ./project

docker:
  image: mcr.microsoft.com/devcontainers/base:ubuntu
  build_args: []

# Coding agent configuration
agent:
  name: {agent}
  version: {agent_version}
  options:
{agent_options}

# Runtime configuration (optional)
# runtime:
#   language: python
#   version: "3.12"
#   package_manager: uv
#   tools: []

# Proxy configuration for corporate networks (optional)
# proxy:
#   http: http://proxy.corp.com:8080
#   https: http://proxy.corp.com:8080
#   no_proxy: localhost,127.0.0.1,.local

# Marketplace configurations (optional)
# marketplaces:
#   omc:
#     url: https://github.com/oh-my-claudecode/marketplace

# Plugin configurations (optional)
# plugins:
#   - marketplace: omc
#     name: oh-my-claudecode
#     activate: true

# Git configuration
git:
  generated: ignored
"#,
        name = project_name,
        agent = agent,
        agent_version = agent_version,
        agent_options = agent_options_section,
    )
}

/// Generate agent-specific options YAML block (indented for embedding in isolde.yaml)
fn agent_options_yaml(agent: &str) -> String {
    match agent {
        "claude-code" => {
            "    provider: anthropic\n    models: \"haiku:claude-3-5-haiku-20241022,sonnet:claude-3-5-sonnet-20241022,opus:claude-3-5-sonnet-20241022\"".to_string()
        }
        _ => {
            "    {}".to_string()
        }
    }
}

/// Generate configuration from a preset
fn generate_config_from_preset(project_name: &str, preset_name: &str) -> Result<String> {
    // Try to load presets.yaml from the current directory or template repository
    let preset_yaml = load_presets_yaml()?;

    // Parse the preset configuration
    let preset = find_preset(&preset_yaml, preset_name)?;

    // Generate config based on preset (presets always use claude-code agent)
    let agent_options_section = agent_options_yaml("claude-code");
    let config = format!(
        r#"# Isolde Configuration for {name}
# Generated from preset: {preset}
version: "0.1"

name: {name}
workspace:
  dir: ./project

docker:
  image: mcr.microsoft.com/devcontainers/base:ubuntu
  build_args: []

# Coding agent configuration
agent:
  name: claude-code
  version: latest
  options:
{agent_options}

runtime:
  language: {lang}
  version: "{version}"
  package_manager: auto
  tools: {tools}

# Plugin configurations
plugins:
{plugins}

# Git configuration
git:
  generated: ignored
"#,
        name = project_name,
        preset = preset_name,
        agent_options = agent_options_section,
        lang = preset.template,
        version = preset.lang_version,
        tools = serde_yaml::to_string(&preset.features).unwrap_or_else(|_| "[]".to_string()),
        plugins = preset
            .claude_plugins
            .iter()
            .map(|p| format!("  - marketplace: omc\n    name: {}\n    activate: true", p))
            .collect::<Vec<_>>()
            .join("\n")
    );

    Ok(config)
}

/// Search upward from a directory for presets.yaml
fn search_presets_upward(start: &std::path::Path) -> Option<PathBuf> {
    let mut dir = start;
    loop {
        let candidate = dir.join("presets.yaml");
        if candidate.exists() {
            return Some(candidate);
        }
        match dir.parent() {
            Some(parent) => dir = parent,
            None => return None,
        }
    }
}

/// Load presets.yaml from the current directory, binary location, or by searching upward
fn load_presets_yaml() -> Result<String> {
    // Try current directory first
    let local_path = PathBuf::from("presets.yaml");
    if local_path.exists() {
        return fs::read_to_string(&local_path).map_err(|e| {
            Error::FileError(std::io::Error::new(
                std::io::ErrorKind::NotFound,
                format!("Failed to read presets.yaml: {}", e),
            ))
        });
    }

    // Search upward from current directory
    if let Ok(current_dir) = std::env::current_dir() {
        if let Some(found) = search_presets_upward(&current_dir) {
            return fs::read_to_string(&found).map_err(|e| {
                Error::FileError(std::io::Error::new(
                    std::io::ErrorKind::NotFound,
                    format!("Failed to read presets.yaml: {}", e),
                ))
            });
        }
    }

    // Search upward from the binary's location (handles cases where cwd is outside the repo)
    if let Ok(exe_path) = std::env::current_exe() {
        if let Some(exe_dir) = exe_path.parent() {
            if let Some(found) = search_presets_upward(exe_dir) {
                return fs::read_to_string(&found).map_err(|e| {
                    Error::FileError(std::io::Error::new(
                        std::io::ErrorKind::NotFound,
                        format!("Failed to read presets.yaml: {}", e),
                    ))
                });
            }
        }
    }

    Err(Error::InvalidTemplate(
        "presets.yaml not found. Please run this command from the Isolde repository root.".to_string(),
    ))
}

/// Find and extract a preset from the YAML
fn find_preset(yaml: &str, preset_name: &str) -> Result<PresetData> {
    use isolde_core::config::Preset;

    // Parse the presets YAML
    let value: serde_yaml::Value = serde_yaml::from_str(yaml)
        .map_err(|e| Error::InvalidTemplate(format!("Failed to parse presets.yaml: {}", e)))?;

    let presets = value
        .get("presets")
        .and_then(|v| v.as_mapping())
        .ok_or_else(|| Error::InvalidTemplate("No presets found in presets.yaml".to_string()))?;

    let preset_value = presets
        .get(serde_yaml::Value::String(preset_name.to_string()))
        .ok_or_else(|| Error::PresetNotFound(preset_name.to_string()))?;

    // Try to parse as Preset
    let preset: Preset = serde_yaml::from_value(preset_value.clone())
        .map_err(|e| Error::InvalidTemplate(format!("Failed to parse preset '{}': {}", preset_name, e)))?;

    Ok(PresetData {
        template: preset.template.clone(),
        lang_version: preset.lang_version.clone(),
        features: preset.features.clone(),
        claude_plugins: preset.claude_plugins.clone(),
    })
}

/// Simplified preset data structure
#[derive(Debug, Clone)]
struct PresetData {
    template: String,
    lang_version: String,
    features: Vec<String>,
    claude_plugins: Vec<String>,
}

/// Valid template names
const VALID_TEMPLATES: &[&str] = &["python", "nodejs", "rust", "go", "minimal", "generic"];

/// Validate language version for the given template
fn validate_lang_version(template: Option<&str>, version: &str) -> Result<()> {
    // "latest" and empty string are always valid (use template defaults)
    if version == "latest" || version.is_empty() {
        return Ok(());
    }

    let is_valid = match template {
        Some("python") => {
            // Python versions: 3.x or 3.x.y where x is a reasonable minor version
            version.starts_with("3.") && {
                let minor = version.trim_start_matches("3.");
                let minor_num: Option<u32> = minor.split('.').next().and_then(|s| s.parse().ok());
                minor_num.map_or(false, |n| n <= 20)
            }
        }
        Some("nodejs") => {
            // Node.js versions: single number (18, 20, 22, etc.) or major.minor
            let major: Option<u32> = version.split('.').next().and_then(|s| s.parse().ok());
            major.map_or(false, |n| n >= 14 && n <= 30)
        }
        Some("rust") => {
            // Rust: stable, nightly, beta, or semver
            matches!(version, "stable" | "nightly" | "beta") || {
                let parts: Vec<&str> = version.split('.').collect();
                parts.len() >= 2 && parts[0].parse::<u32>().is_ok()
            }
        }
        Some("go") => {
            // Go versions: 1.x or 1.x.y
            version.starts_with("1.") && {
                let minor = version.trim_start_matches("1.");
                let minor_num: Option<u32> = minor.split('.').next().and_then(|s| s.parse().ok());
                minor_num.map_or(false, |n| n <= 30)
            }
        }
        _ => {
            // For unknown templates or minimal, do a basic sanity check
            // Version numbers shouldn't have major version > 50
            let major: Option<u32> = version.split('.').next().and_then(|s| s.parse().ok());
            major.map_or(true, |n| n <= 50)
        }
    };

    if is_valid {
        Ok(())
    } else {
        Err(Error::Other(format!(
            "Invalid language version '{}' for template '{}'",
            version,
            template.unwrap_or("unknown")
        )))
    }
}

/// Run the init command
pub fn run(opts: InitOptions) -> Result<()> {
    let config_path = opts.cwd.join("isolde.yaml");

    // Check if isolde.yaml already exists
    if config_path.exists() {
        return Err(Error::Other(format!(
            "isolde.yaml already exists at {}. Use --force to overwrite.",
            config_path.display()
        )));
    }

    // Validate template name if provided
    if let Some(ref template) = opts.template {
        if !VALID_TEMPLATES.contains(&template.as_str()) {
            return Err(Error::InvalidTemplate(format!(
                "Unknown template '{}'. Valid templates: {}",
                template,
                VALID_TEMPLATES.join(", ")
            )));
        }
    }

    // Validate lang_version if provided
    if let Some(ref version) = opts.lang_version {
        if let Err(e) = validate_lang_version(opts.template.as_deref(), version) {
            return Err(e);
        }
    }

    // Determine project name
    let project_name = opts.name.unwrap_or_else(|| {
        opts
            .cwd
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("my-project")
            .to_string()
    });

    // Validate proxy URLs if provided
    if let Some(ref proxy_url) = opts.http_proxy {
        if !proxy_url.starts_with("http://") && !proxy_url.starts_with("https://") {
            return Err(Error::InvalidTemplate(format!(
                "Invalid proxy URL '{}': proxy URL must start with http:// or https://",
                proxy_url
            )));
        }
    }
    if let Some(ref proxy_url) = opts.https_proxy {
        if !proxy_url.starts_with("http://") && !proxy_url.starts_with("https://") {
            return Err(Error::InvalidTemplate(format!(
                "Invalid proxy URL '{}': proxy URL must start with http:// or https://",
                proxy_url
            )));
        }
    }

    // Generate configuration
    let config_content = if let Some(preset) = &opts.preset {
        print!(
            "{}",
            format!("Loading preset '{}'...\n", preset.cyan()).dimmed()
        );
        generate_config_from_preset(&project_name, preset)?
    } else if let Some(ref template) = opts.template {
        generate_config_from_template(&project_name, template, &opts.agent, &opts.agent_version)
    } else {
        generate_default_config(&project_name, &opts.agent, &opts.agent_version)
    };

    // Validate the configuration
    let config = Config::from_str(&config_content)?;

    // Show preview
    println!("\n{}", "Configuration preview:".bold());
    println!("{}", "─".repeat(50));
    println!("  Name: {}", config.name.cyan());
    println!("  Schema Version: {}", config.version);
    println!("  Workspace: {}", config.workspace_dir());
    println!("  Docker Image: {}", config.docker_image());
    println!("  Agent: {}", config.agent_name());
    if let Some(runtime) = config.runtime() {
        println!(
            "  Runtime: {} {}",
            runtime.language(),
            runtime.version()
        );
    }
    println!("{}", "─".repeat(50));

    // Ask for confirmation
    if !opts.yes {
        print!(
            "\n{}",
            "Create isolde.yaml with this configuration? [Y/n] ".bold()
        );
        use std::io::Write;
        std::io::stdout().flush().unwrap();

        let mut input = String::new();
        std::io::stdin()
            .read_line(&mut input)
            .map_err(|e| Error::Other(format!("Failed to read input: {}", e)))?;

        let input = input.trim().to_lowercase();
        if !input.is_empty() && input != "y" && input != "yes" {
            println!("{}", "Aborted.".yellow());
            return Ok(());
        }
    }

    // Write configuration file
    fs::write(&config_path, config_content)
        .map_err(|e| Error::FileError(std::io::Error::new(std::io::ErrorKind::Other, format!("Failed to write isolde.yaml: {}", e))))?;

    println!(
        "\n{} {}",
        "✔".green(),
        format!("Created isolde.yaml at {}", config_path.display()).green()
    );
    println!(
        "{}",
        "Run 'isolde sync' to generate the devcontainer configuration.".dimmed()
    );

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_default_config() {
        let config = generate_default_config("test-project", "claude-code", "latest");
        assert!(config.contains("name: test-project"));
        assert!(config.contains("workspace:"));
        assert!(config.contains("docker:"));
        assert!(config.contains("agent:"));
        assert!(config.contains("name: claude-code"));
        assert!(!config.contains("claude:"));
    }

    #[test]
    fn test_generate_default_config_codex() {
        let config = generate_default_config("test-project", "codex", "latest");
        assert!(config.contains("name: codex"));
        assert!(!config.contains("provider: anthropic"));
    }

    #[test]
    fn test_generate_config_from_template() {
        let config = generate_config_from_template("my-app", "python", "claude-code", "latest");
        assert!(config.contains("name: my-app"));
        assert!(config.contains("agent:"));
        assert!(config.contains("name: claude-code"));
        assert!(config.contains("python"));
    }

    #[test]
    fn test_init_options_default() {
        let opts = InitOptions::default();
        assert!(opts.template.is_none());
        assert!(opts.preset.is_none());
        assert!(!opts.yes);
        assert_eq!(opts.agent, "claude-code");
        assert_eq!(opts.agent_version, "latest");
    }
}
