//! # Devcontainer artifact rendering
//!
//! Pure functions that generate devcontainer configuration files from an Isolde Config.
//! Used by `isolde sync` (CLI) and `isolde diff` (comparison).

use std::fs;
use std::path::{Path, PathBuf};

use crate::config::{AgentConfigView, AgentOptionValue, Config};
use crate::error::{Error, Result};

const DOCKERFILE_BANNER: &str =
    "# ⚠ Auto-generated by Isolde. Do not edit. Run 'isolde sync' to regenerate.\n\n";
const JSON_BANNER: &str =
    "Auto-generated by Isolde. Do not edit. Run 'isolde sync' to regenerate.";
const MARKDOWN_BANNER: &str =
    "<!-- ⚠ Auto-generated by Isolde. Do not edit. Run 'isolde sync' to regenerate. -->";

/// Information about host auth files (for full isolation mode mount generation).
#[derive(Debug, Clone)]
pub struct HostAuthInfo {
    /// Whether ~/.claude/.credentials.json exists
    pub credentials_exist: bool,
    /// Whether ~/.claude/providers/ directory exists
    pub providers_exist: bool,
    /// Whether ~/.claude/provider file exists
    pub provider_file_exists: bool,
}

impl HostAuthInfo {
    /// Detect auth files from the current host environment.
    pub fn detect() -> Self {
        let home = std::env::var("HOME").unwrap_or_default();
        if home.is_empty() {
            return Self::none();
        }
        let base = Path::new(&home).join(".claude");
        Self {
            credentials_exist: base.join(".credentials.json").exists(),
            providers_exist: base.join("providers").exists(),
            provider_file_exists: base.join("provider").exists(),
        }
    }

    /// No auth files detected (for testing or non-full isolation).
    pub fn none() -> Self {
        Self {
            credentials_exist: false,
            providers_exist: false,
            provider_file_exists: false,
        }
    }
}

/// Copy a directory recursively.
pub fn copy_dir_recursive(src: &Path, dst: &Path) -> Result<()> {
    fs::create_dir_all(dst).map_err(|e| {
        Error::FileError(std::io::Error::new(
            std::io::ErrorKind::Other,
            format!("Failed to create directory {}: {}", dst.display(), e),
        ))
    })?;

    for entry in fs::read_dir(src)
        .map_err(|e| Error::FileError(std::io::Error::new(std::io::ErrorKind::Other, e)))?
    {
        let entry = entry?;
        let ty = entry.file_type()?;
        let src_path = entry.path();
        let dst_path = dst.join(entry.file_name());

        if ty.is_dir() {
            copy_dir_recursive(&src_path, &dst_path)?;
        } else {
            fs::copy(&src_path, &dst_path).map_err(|e| {
                Error::FileError(std::io::Error::new(
                    std::io::ErrorKind::Other,
                    format!(
                        "Failed to copy {} to {}: {}",
                        src_path.display(),
                        dst_path.display(),
                        e
                    ),
                ))
            })?;
        }
    }

    Ok(())
}

/// Find the core features directory.
///
/// Search order: ISOLDE_CORE_FEATURES env var, relative paths from cwd,
/// paths relative to executable, XDG data dirs, system-wide paths.
pub fn find_core_features_dir() -> Result<PathBuf> {
    let mut possible_paths = vec![];

    if let Ok(env_path) = std::env::var("ISOLDE_CORE_FEATURES") {
        possible_paths.push(PathBuf::from(env_path));
    }

    possible_paths.push(PathBuf::from("core/features"));
    possible_paths.push(PathBuf::from("../core/features"));
    possible_paths.push(PathBuf::from("../../core/features"));

    if let Ok(exe_path) = std::env::current_exe() {
        if let Some(exe_dir) = exe_path.parent() {
            if let Some(prefix) = exe_dir.parent() {
                possible_paths.push(
                    prefix
                        .join("share")
                        .join("isolde")
                        .join("core")
                        .join("features"),
                );
            }
            possible_paths.push(exe_dir.join("core").join("features"));
            possible_paths.push(
                exe_dir
                    .join("../core/features")
                    .canonicalize()
                    .unwrap_or_else(|_| PathBuf::from("../core/features")),
            );
        }
    }

    if let Ok(home) = std::env::var("HOME") {
        possible_paths.push(PathBuf::from(&home).join(".local/share/isolde/core/features"));
        possible_paths.push(PathBuf::from(home).join(".isolde/core/features"));
    }

    possible_paths.push(PathBuf::from("/usr/local/share/isolde/core/features"));
    possible_paths.push(PathBuf::from("/opt/isolde/core/features"));

    for path in possible_paths {
        if path.exists() {
            return Ok(path);
        }
    }

    Err(Error::PathNotFound(PathBuf::from("core/features")))
}

/// Copy all core features to the destination directory.
///
/// Each subdirectory under `core/features/` is copied to `dest/<feature-name>/`.
/// Existing feature directories at the destination are removed first.
pub fn copy_core_features(dest: &Path) -> Result<()> {
    let core_features = find_core_features_dir()?;

    for entry in fs::read_dir(&core_features)
        .map_err(|e| Error::FileError(std::io::Error::new(std::io::ErrorKind::Other, e)))?
    {
        let entry = entry?;
        let feature_path = entry.path();

        if feature_path.is_dir() {
            let feature_name = feature_path
                .file_name()
                .and_then(|n| n.to_str())
                .ok_or_else(|| Error::Other("Invalid feature name".to_string()))?;

            let feature_dest = dest.join(feature_name);

            if feature_dest.exists() {
                fs::remove_dir_all(&feature_dest).map_err(|e| {
                    Error::FileError(std::io::Error::new(
                        std::io::ErrorKind::Other,
                        format!("Failed to remove {}: {}", feature_dest.display(), e),
                    ))
                })?;
            }

            copy_dir_recursive(&feature_path, &feature_dest)?;
        }
    }

    Ok(())
}

/// Render devcontainer.json content from configuration.
///
/// Builds a complete devcontainer.json with: common-utils, conditional Node.js,
/// language-specific features, proxy, agent feature, plugin manager, mounts,
/// and feature install order.
pub fn render_devcontainer_json(config: &Config, host_auth: &HostAuthInfo) -> Result<String> {
    let proxy = config.proxy();
    let plugins = config.plugins();
    let mut features = serde_json::Map::new();

    // common-utils: match host UID/GID for bind-mounted directories
    features.insert(
        "ghcr.io/devcontainers/features/common-utils:2".to_string(),
        serde_json::json!({
            "installZsh": false,
            "installOhMyZsh": false,
            "upgradePackages": false,
            "username": "${localEnv:USER}",
            "userUid": "automatic",
            "userGid": "automatic"
        }),
    );

    // Node.js for agents that need npm — add once if any agent requires it.
    // Skip if the project language is already nodejs/javascript.
    let agents = config.agents();
    let any_agent_needs_node = agents
        .iter()
        .any(|a| matches!(a.name(), "claude-code" | "codex" | "opencode"));
    let lang_is_node = config
        .runtime()
        .map(|r| matches!(r.language(), "nodejs" | "javascript"))
        .unwrap_or(false);

    if any_agent_needs_node && !lang_is_node {
        features.insert(
            "ghcr.io/devcontainers/features/node:1".to_string(),
            serde_json::json!({
                "version": "lts",
                "nodeGypDependencies": true,
                "npxInstallCachedPackages": true
            }),
        );
    }

    // Language-specific features
    if let Some(runtime) = config.runtime() {
        match runtime.language() {
            "python" => {
                features.insert(
                    "ghcr.io/devcontainers/features/python:1".to_string(),
                    serde_json::json!({
                        "version": runtime.version(),
                        "installTools": true
                    }),
                );
            }
            "nodejs" | "javascript" => {
                features.insert(
                    "ghcr.io/devcontainers/features/node:1".to_string(),
                    serde_json::json!({
                        "version": runtime.version()
                    }),
                );
            }
            "rust" => {
                features.insert(
                    "ghcr.io/devcontainers/features/rust:1".to_string(),
                    serde_json::json!({
                        "version": runtime.version()
                    }),
                );
            }
            "go" => {
                features.insert(
                    "ghcr.io/devcontainers/features/go:1".to_string(),
                    serde_json::json!({
                        "version": runtime.version()
                    }),
                );
            }
            _ => {}
        }
    }

    // Proxy feature
    if let Some(proxy) = &proxy {
        features.insert(
            "./features/proxy".to_string(),
            serde_json::json!({
                "http_proxy": proxy.http(),
                "https_proxy": proxy.https(),
                "no_proxy": proxy.no_proxy(),
                "enabled": true
            }),
        );
    }

    // Coding agent features — one entry per configured agent
    for agent in &agents {
        let mut agent_opts = serde_json::Map::new();
        agent_opts.insert(
            "version".to_string(),
            serde_json::Value::String(agent.version().to_string()),
        );
        for (key, value) in agent.options() {
            let json_val = match value {
                AgentOptionValue::Str(s) => serde_json::Value::String(s.clone()),
                AgentOptionValue::Map(m) => {
                    let csv = m
                        .iter()
                        .map(|(k, v)| format!("{}:{}", k, v))
                        .collect::<Vec<_>>()
                        .join(",");
                    serde_json::Value::String(csv)
                }
            };
            agent_opts.insert(key.clone(), json_val);
        }
        if let Some(proxy) = &proxy {
            if let Some(h) = proxy.http() {
                agent_opts.insert(
                    "http_proxy".to_string(),
                    serde_json::Value::String(h.clone()),
                );
            }
            if let Some(h) = proxy.https() {
                agent_opts.insert(
                    "https_proxy".to_string(),
                    serde_json::Value::String(h.clone()),
                );
            }
        }
        let agent_feature_path = format!("./features/{}", agent.name());
        features.insert(agent_feature_path, serde_json::Value::Object(agent_opts));
    }

    // Plugin manager feature (only if any agent is claude-code with plugins)
    let has_claude = agents.iter().any(|a| a.name() == "claude-code");
    if has_claude && !plugins.is_empty() {
        let activate: Vec<&str> = plugins
            .iter()
            .filter(|p| p.activate)
            .map(|p| p.name.as_str())
            .collect();
        let deactivate: Vec<&str> = plugins
            .iter()
            .filter(|p| !p.activate)
            .map(|p| p.name.as_str())
            .collect();

        features.insert(
            "./features/plugin-manager".to_string(),
            serde_json::json!({
                "activate_plugins": activate,
                "deactivate_plugins": deactivate
            }),
        );
    }

    // Feature install order
    let mut override_order: Vec<String> = vec![];
    if proxy.is_some() {
        override_order.push("./features/proxy".to_string());
    }
    for agent in &agents {
        override_order.push(format!("./features/{}", agent.name()));
    }
    if has_claude && !plugins.is_empty() {
        override_order.push("./features/plugin-manager".to_string());
    }

    // Mounts (uses host auth info for full isolation)
    let mounts = crate::mounts::generate_mounts(
        config,
        host_auth.credentials_exist,
        host_auth.providers_exist,
        host_auth.provider_file_exists,
    );

    let devcontainer = serde_json::json!({
        "_comment": JSON_BANNER,
        "name": format!("{} - Isolde Environment", config.name),
        "build": {
            "dockerfile": "Dockerfile",
            "context": "..",
            "args": {
                "USERNAME": "${localEnv:USER}"
            }
        },
        "features": features,
        "overrideFeatureInstallOrder": override_order,
        "customizations": {
            "vscode": {
                "extensions": ["anthropic.claude-code"],
                "settings": {
                    "terminal.integrated.defaultProfile.linux": "bash"
                }
            }
        },
        "mounts": mounts,
        "remoteUser": "${localEnv:USER}",
        "workspaceFolder": format!("/workspaces/{}", config.name)
    });

    serde_json::to_string_pretty(&devcontainer)
        .map_err(|e| Error::Other(format!("Failed to serialize devcontainer.json: {}", e)))
}

/// Render Dockerfile content from configuration.
pub fn render_dockerfile(config: &Config) -> Result<String> {
    let banner = DOCKERFILE_BANNER;
    let dockerfile = format!(
        r#"{}ARG BASE_IMAGE={}
FROM ${{BASE_IMAGE}}

# User arguments with defaults
ARG USERNAME=user

# Set DEBIAN_FRONTEND for non-interactive apt
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /workspaces

# If the base image has a 'vscode' user at UID 1000 and the requested user is different,
# reassign vscode to a high UID so that updateRemoteUserUID can give UID 1000 to USERNAME.
# This ensures bind-mounted host directories (owned by UID 1000) appear with the correct
# owner inside the container without needing chown on the bind mount.
RUN if [ "${{USERNAME}}" != "vscode" ] && id vscode >/dev/null 2>&1; then \
        userdel -r vscode 2>/dev/null || true; \
        groupdel vscode 2>/dev/null || true; \
    fi
"#,
        banner,
        config.docker_image()
    );

    Ok(dockerfile)
}

/// Render CLAUDE.md content from configuration.
pub fn render_claude_md(config: &Config) -> Result<String> {
    let agents = config.agents();
    let agent_names: Vec<&str> = agents.iter().map(|a| a.name()).collect();
    let agent_label = if agent_names.len() == 1 { "Agent" } else { "Agents" };
    let agent_list = agent_names.join(", ");

    let mut content = format!(
        r#"{}

# Claude Code Configuration for {}

This file provides guidance to Claude Code (claude.ai/code) when working with code in this repository.

## Project Overview

**{}** - Schema Version {}

This is an Isolde-managed isolated development environment.

## Configuration

- **Docker Image**: {}
- **{}**: {}
- **Workspace Directory**: {}
"#,
        MARKDOWN_BANNER,
        config.name,
        config.name,
        config.version,
        config.docker_image(),
        agent_label,
        agent_list,
        config.workspace_dir()
    );

    if let Some(runtime) = config.runtime() {
        content.push_str(&format!(
            r#"
## Runtime Environment

- **Language**: {} {}
- **Package Manager**: {}
"#,
            runtime.language(),
            runtime.version(),
            runtime.package_manager()
        ));

        if !runtime.tools().is_empty() {
            content.push_str("\n### Tools\n");
            for tool in runtime.tools() {
                content.push_str(&format!("- {}\n", tool));
            }
        }
    }

    let plugins = config.plugins();
    if !plugins.is_empty() {
        content.push_str("\n## Claude Plugins\n");
        for plugin in &plugins {
            let status = if plugin.activate { "✓" } else { "✗" };
            content.push_str(&format!(
                "- {} {} (from marketplace: {})\n",
                status, plugin.name, plugin.marketplace
            ));
        }
    }

    if let Some(proxy) = config.proxy() {
        content.push_str(
            r#"

## Proxy Configuration

This project is configured to work with a corporate proxy.
"#,
        );
        if let Some(http) = proxy.http() {
            content.push_str(&format!("- HTTP Proxy: {}\n", http));
        }
        if let Some(https) = proxy.https() {
            content.push_str(&format!("- HTTPS Proxy: {}\n", https));
        }
        if let Some(no_proxy) = proxy.no_proxy() {
            content.push_str(&format!("- No Proxy: {}\n", no_proxy));
        }
    }

    content.push_str(
        r#"

## Development Workflow

1. **Build the devcontainer**:
   ```bash
   docker build -t <image-name> .devcontainer
   ```

2. **Start development**:
   - Use VS Code Dev Containers or
   - Run: `docker run -it --rm -v $(pwd):/workspaces/<project> <image-name>`

3. **Use Claude Code**:
   ```bash
   claude "help me understand this codebase"
   ```

## Notes

- Configuration is managed by Isolde
- Run `isolde sync` to regenerate configuration
- Do not manually edit generated files in `.devcontainer/`
"#,
    );

    Ok(content)
}

/// Render native settings file for an agent's permissions.
/// Returns Ok(Some((relative_path, content))) or Ok(None) if no permissions configured.
pub fn render_agent_settings(agent: &AgentConfigView) -> Result<Option<(String, String)>> {
    let perms = match agent.permissions() {
        Some(p) => p,
        None => return Ok(None),
    };

    /// Build a settings map with the standard banner comment.
    fn new_settings_map() -> serde_json::Map<String, serde_json::Value> {
        let mut settings = serde_json::Map::new();
        settings.insert(
            "_comment".to_string(),
            serde_json::Value::String(JSON_BANNER.to_string()),
        );
        settings
    }

    fn serialize(settings: &serde_json::Map<String, serde_json::Value>) -> Result<String> {
        serde_json::to_string_pretty(settings)
            .map_err(|e| Error::Other(format!("Failed to serialize agent settings: {e}")))
    }

    match agent.name() {
        "claude-code" => {
            let mut settings = new_settings_map();
            if !perms.allowed_tools.is_empty() {
                settings.insert(
                    "allowedTools".to_string(),
                    serde_json::json!(&perms.allowed_tools),
                );
            }
            if !perms.allowed_commands.is_empty() {
                settings.insert(
                    "allowedCommands".to_string(),
                    serde_json::json!(&perms.allowed_commands),
                );
            }
            if !perms.deny_commands.is_empty() {
                settings.insert(
                    "denyCommands".to_string(),
                    serde_json::json!(&perms.deny_commands),
                );
            }
            Ok(Some((".claude/settings.json".to_string(), serialize(&settings)?)))
        }
        "opencode" => {
            let mut settings = new_settings_map();
            if !perms.allowed_tools.is_empty() {
                settings.insert(
                    "tools".to_string(),
                    serde_json::json!(&perms.allowed_tools),
                );
            }
            if !perms.deny_commands.is_empty() {
                eprintln!("⚠ Agent 'opencode' does not support deny_commands — ignoring");
            }
            Ok(Some(("opencode.json".to_string(), serialize(&settings)?)))
        }
        "codex" => {
            if !perms.allowed_tools.is_empty() {
                eprintln!("⚠ Agent 'codex' does not support allowed_tools — ignoring");
            }
            if !perms.deny_commands.is_empty() {
                eprintln!("⚠ Agent 'codex' does not support deny_commands — ignoring");
            }
            Ok(None)
        }
        _ => Ok(None),
    }
}

/// List relative paths of all artifacts that `isolde sync` would generate.
///
/// Paths are relative to the project root.
/// The caller is responsible for checking which paths already exist on disk
/// to classify them as "would create" vs. "would modify".
pub fn expected_artifacts(config: &Config) -> Vec<String> {
    let mut paths = vec![
        ".devcontainer/devcontainer.json".to_string(),
        ".devcontainer/Dockerfile".to_string(),
        ".claude/CLAUDE.md".to_string(),
    ];

    // Feature directory per agent
    let agents = config.agents();
    for agent in &agents {
        paths.push(format!(".devcontainer/features/{}", agent.name()));
    }

    // Proxy feature — only when proxy is configured
    if config.proxy().is_some() {
        paths.push(".devcontainer/features/proxy".to_string());
    }

    // Plugin-manager — only if any claude-code agent with plugins
    let has_claude_with_plugins = agents.iter().any(|a| a.name() == "claude-code")
        && !config.plugins().is_empty();
    if has_claude_with_plugins {
        paths.push(".devcontainer/features/plugin-manager".to_string());
    }

    // Settings files for agents with permissions
    for agent in &agents {
        if agent.permissions().is_some() {
            match agent.name() {
                "claude-code" => paths.push(".claude/settings.json".to_string()),
                "opencode" => paths.push("opencode.json".to_string()),
                _ => {}
            }
        }
    }

    paths
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_host_auth_info_none() {
        let info = HostAuthInfo::none();
        assert!(!info.credentials_exist);
        assert!(!info.providers_exist);
        assert!(!info.provider_file_exists);
    }

    #[test]
    fn test_copy_dir_recursive() {
        let temp_dir = tempfile::tempdir().unwrap();
        let src = temp_dir.path().join("src");
        let dst = temp_dir.path().join("dst");

        fs::create_dir_all(&src).unwrap();
        fs::write(src.join("file1.txt"), "content1").unwrap();
        fs::create_dir_all(src.join("subdir")).unwrap();
        fs::write(src.join("subdir/file2.txt"), "content2").unwrap();

        copy_dir_recursive(&src, &dst).unwrap();

        assert!(dst.join("file1.txt").exists());
        assert_eq!(
            fs::read_to_string(dst.join("file1.txt")).unwrap(),
            "content1"
        );
        assert!(dst.join("subdir/file2.txt").exists());
        assert_eq!(
            fs::read_to_string(dst.join("subdir/file2.txt")).unwrap(),
            "content2"
        );
    }

    fn test_config(yaml: &str) -> Config {
        Config::from_str(yaml).unwrap()
    }

    fn minimal_config() -> Config {
        test_config(
            r#"
version: "0.1"
name: test
workspace:
  dir: .
docker:
  image: ubuntu:latest
claude:
  provider: anthropic
"#,
        )
    }

    #[test]
    fn test_render_devcontainer_json_basic() {
        let config = minimal_config();
        let result = render_devcontainer_json(&config, &HostAuthInfo::none()).unwrap();
        assert!(result.contains("\"features\""));
        assert!(result.contains("claude-code"));
        assert!(result.contains("common-utils"));
    }

    #[test]
    fn test_render_devcontainer_json_with_python() {
        let config = test_config(
            r#"
version: "0.1"
name: test
docker:
  image: ubuntu:latest
runtime:
  language: python
  version: "3.12"
  package_manager: uv
"#,
        );
        let result = render_devcontainer_json(&config, &HostAuthInfo::none()).unwrap();
        assert!(result.contains("ghcr.io/devcontainers/features/python:1"));
        assert!(result.contains("3.12"));
    }

    #[test]
    fn test_render_dockerfile() {
        let config = minimal_config();
        let dockerfile = render_dockerfile(&config).unwrap();
        assert!(dockerfile.contains("ARG BASE_IMAGE=ubuntu:latest"));
        assert!(dockerfile.contains("FROM ${BASE_IMAGE}"));
        assert!(dockerfile.contains("ARG USERNAME=user"));
    }

    #[test]
    fn test_render_claude_md() {
        let config = test_config(
            r#"
version: "0.1"
name: test-project
docker:
  image: ubuntu:latest
runtime:
  language: python
  version: "3.12"
  package_manager: uv
"#,
        );
        let claude_md = render_claude_md(&config).unwrap();
        assert!(claude_md.contains("test-project"));
        assert!(claude_md.contains("python 3.12"));
    }

    #[test]
    fn test_banner_in_dockerfile() {
        let config = minimal_config();
        let dockerfile = render_dockerfile(&config).unwrap();
        assert!(dockerfile.starts_with("# ⚠ Auto-generated by Isolde. Do not edit."));
    }

    #[test]
    fn test_banner_in_devcontainer_json() {
        let config = minimal_config();
        let host_auth = HostAuthInfo::none();
        let json_str = render_devcontainer_json(&config, &host_auth).unwrap();
        assert!(json_str.contains("\"_comment\""));
        assert!(json_str.contains("Auto-generated by Isolde"));
    }

    #[test]
    fn test_banner_in_claude_md() {
        let config = minimal_config();
        let claude_md = render_claude_md(&config).unwrap();
        assert!(claude_md.starts_with("<!-- ⚠ Auto-generated by Isolde."));
    }

    #[test]
    fn test_render_claude_settings() {
        let yaml = r#"
version: "0.1"
name: test-app
docker:
  image: ubuntu:latest
agents:
  - name: claude-code
    version: latest
    permissions:
      allowed_tools: ["bash", "edit"]
      allowed_commands: ["cargo test"]
      deny_commands: ["rm -rf"]
"#;
        let config = Config::from_str(yaml).unwrap();
        let agents = config.agents();
        let result = render_agent_settings(&agents[0]).unwrap();
        assert!(result.is_some());
        let (path, content) = result.unwrap();
        assert_eq!(path, ".claude/settings.json");
        assert!(content.contains("allowedTools"));
        assert!(content.contains("bash"));
        assert!(content.contains("_comment"));
    }

    #[test]
    fn test_render_opencode_settings() {
        let yaml = r#"
version: "0.1"
name: test-app
docker:
  image: ubuntu:latest
agents:
  - name: opencode
    version: latest
    permissions:
      allowed_tools: ["bash", "read"]
"#;
        let config = Config::from_str(yaml).unwrap();
        let agents = config.agents();
        let result = render_agent_settings(&agents[0]).unwrap();
        assert!(result.is_some());
        let (path, content) = result.unwrap();
        assert_eq!(path, "opencode.json");
        assert!(content.contains("tools"));
        assert!(content.contains("bash"));
    }

    #[test]
    fn test_render_agent_settings_no_permissions() {
        let yaml = r#"
version: "0.1"
name: test-app
docker:
  image: ubuntu:latest
agents:
  - name: claude-code
    version: latest
"#;
        let config = Config::from_str(yaml).unwrap();
        let agents = config.agents();
        let result = render_agent_settings(&agents[0]).unwrap();
        assert!(result.is_none());
    }

    #[test]
    fn test_render_claude_md_multi_agent() {
        let yaml = r#"
version: "0.1"
name: multi-test
docker:
  image: ubuntu:latest
agents:
  - name: claude-code
    version: latest
  - name: opencode
    version: latest
"#;
        let config = Config::from_str(yaml).unwrap();
        let claude_md = render_claude_md(&config).unwrap();
        assert!(claude_md.contains("Agents"));
        assert!(claude_md.contains("claude-code, opencode"));
    }

    #[test]
    fn test_render_devcontainer_json_multi_agent() {
        let yaml = r#"
version: "0.1"
name: multi-test
docker:
  image: ubuntu:latest
agents:
  - name: claude-code
    version: latest
  - name: opencode
    version: latest
"#;
        let config = Config::from_str(yaml).unwrap();
        let host_auth = HostAuthInfo::none();
        let json_str = render_devcontainer_json(&config, &host_auth).unwrap();
        assert!(json_str.contains("./features/claude-code"));
        assert!(json_str.contains("./features/opencode"));
    }

    #[test]
    fn test_render_node_dedup_multi_agent() {
        let yaml = r#"
version: "0.1"
name: node-dedup-test
docker:
  image: ubuntu:latest
agents:
  - name: claude-code
    version: latest
  - name: codex
    version: latest
"#;
        let config = Config::from_str(yaml).unwrap();
        let host_auth = HostAuthInfo::none();
        let json_str = render_devcontainer_json(&config, &host_auth).unwrap();
        // Node feature should appear exactly once
        assert_eq!(
            json_str
                .matches("ghcr.io/devcontainers/features/node")
                .count(),
            1
        );
    }

    #[test]
    fn test_render_with_proxy() {
        let yaml = r#"
version: "0.1"
name: proxy-test
docker:
  image: ubuntu:latest
proxy:
  http: "http://proxy:8080"
  https: "http://proxy:8080"
"#;
        let config = Config::from_str(yaml).unwrap();
        let host_auth = HostAuthInfo::none();
        let json_str = render_devcontainer_json(&config, &host_auth).unwrap();
        assert!(json_str.contains("./features/proxy"));
    }

    #[test]
    fn test_render_with_codex_agent() {
        let yaml = r#"
version: "0.1"
name: codex-test
docker:
  image: ubuntu:latest
agent:
  name: codex
  version: latest
"#;
        let config = Config::from_str(yaml).unwrap();
        let host_auth = HostAuthInfo::none();
        let json_str = render_devcontainer_json(&config, &host_auth).unwrap();
        assert!(json_str.contains("./features/codex"));
    }

    #[test]
    fn test_render_with_opencode_agent() {
        let yaml = r#"
version: "0.1"
name: opencode-test
docker:
  image: ubuntu:latest
agent:
  name: opencode
  version: latest
"#;
        let config = Config::from_str(yaml).unwrap();
        let host_auth = HostAuthInfo::none();
        let json_str = render_devcontainer_json(&config, &host_auth).unwrap();
        assert!(json_str.contains("./features/opencode"));
    }

    #[test]
    fn test_render_with_plugins() {
        let yaml = r#"
version: "0.1"
name: plugin-test
docker:
  image: ubuntu:latest
agent:
  name: claude-code
  version: latest
marketplaces:
  omc:
    url: "https://registry.example.com"
plugins:
  - marketplace: omc
    name: test-plugin
    activate: true
"#;
        let config = Config::from_str(yaml).unwrap();
        let artifacts = expected_artifacts(&config);
        assert!(artifacts.contains(&".devcontainer/features/plugin-manager".to_string()));
    }

    #[test]
    fn test_expected_artifacts() {
        let config = minimal_config();
        let artifacts = expected_artifacts(&config);
        assert!(artifacts.contains(&".devcontainer/devcontainer.json".to_string()));
        assert!(artifacts.contains(&".devcontainer/Dockerfile".to_string()));
        assert!(artifacts.contains(&".claude/CLAUDE.md".to_string()));
        // minimal_config uses claude-code agent
        assert!(artifacts.contains(&".devcontainer/features/claude-code".to_string()));
        // no proxy configured → no proxy feature
        assert!(!artifacts.contains(&".devcontainer/features/proxy".to_string()));
        // no plugins → no plugin-manager
        assert!(!artifacts.contains(&".devcontainer/features/plugin-manager".to_string()));
    }
}
